insert into "tbl_aluno" (id_aluno, situacao, id_usuario) values (5835, 'pendente', 5)
insert into "tbl_aluno" (id_aluno, situacao, id_usuario) values (2484, 'pendente', 6)
insert into "tbl_aluno" (id_aluno, situacao, id_usuario) values (5573, 'pendente', 7)
insert into "tbl_aluno" (id_aluno, situacao, id_usuario) values (3348, 'pendente', 8)
insert into "tbl_aluno" (id_aluno, situacao, id_usuario) values (5078, 'pendente', 9)
insert into "tbl_aluno" (id_aluno, situacao, id_usuario) values (6519, 'pendente', 10)
